version: '3.8'

services:
  inditex-task:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - h2-db

  h2-db:
    image: oscarfonts/h2
    container_name: h2-db
    ports:
      - "8082:8082"
    environment:
      H2_OPTIONS: "-tcp -tcpAllowOthers -web -webAllowOthers"