server:
  port: 3000
  error:
    include-message: always

comms:
  api:
    version: "/v1"

#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG

springdoc:
  default-produces-media-type: application/json

spring:
  application:
    name: Inditex-task
  profiles:
    active:
      - local
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

swagger:
  application-url: http://localhost:${server.port}
  title: ${spring.application.name}
  version: 0.3.5
  application-description: Documentation of the Inditex task endpoint

# Local profile settings
---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:file:./src/main/resources/db/InditexPricingTaskDb
    driverClassName: org.h2.Driver
    username: ${comms.api.user-name}
    password: ${comms.api.pass}
    batch:
      jdbc:
        initialize-schema: always

comms:
  api: # Credentials just for local env
    user-name: "Enrique"
    pass: "inditexTask"

---
# Test profile settings

spring:
  config:
    activate:
      on-profile: test
  security:
    enabled: false

  datasource:
    url: jdbc:h2:file:./src/main/resources/db/InditexPricingTaskDb
    driverClassName: org.h2.Driver
    username: ${comms.api.user-name}
    password: ${comms.api.pass}
    batch:
      jdbc:
        initialize-schema: always

comms:
  api: # Credentials just for local env
    user-name: "Enrique"
    pass: "inditexTask"